name = "RollingFunctions"
uuid = "b0e4dd01-7b14-53d8-9b45-175a3e362653"
repo = "https://github.com/JeffreySarnoff/RollingFunctions.jl.git"
author = "Jeffrey Sarnoff"
license = "MIT"
version = "v0.3.1"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
